# -*- coding: utf-8 -*-
"""footballProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12jmbANG5UVNPymofOlhVpLn7d5sFPZkl
"""

squad_data = [
    [
        'Salem Al-Dawsari',      #name
        'Al Hilal',             #club name
        'FW',                   #position
        '10',                   #number
        'Saudi Arabia'         #country
    ],
    [
        'Neymar Jr.',           #name
        'Al Hilal',             #club name
        'FW',                   #position
        '11',                   #number
        'Brazil'                #country
    ],
    [
        'Yassine Bounou',       #name
        'Al Hilal',             #club name
        'GK',                   #position
        '1',                    #number
        'Morocco'               #country
    ],
    [
        'Mohammed Al-Owais',    #name
        'Al Hilal',             #club name
        'GK',                   #position
        '21',                   #number
        'Saudi Arabia'          #country
    ],
    [
        'Malcom',               #name
        'Al Hilal',             #club name
        'RW',                   #position
        '77',                   #number
        'Brazil'                #country
    ]
]

# Convert the list of lists to a list of dictionaries
def squad_as_dict(squad_data):
   squad_dict = []
   for player in squad_data:
    players =   {
        'name': player[0],
        'club': player[1],
        'position': player[2],
        'number': player[3],
        'country': player[4]
    }
    squad_dict.append(players)
    return squad_dict

# Function to group players by position
def group_by_position(squad_data):
    squad = squad_as_dict(squad_data)
    by_position = {}
    for player in squad:
        position = player['position']
        by_position.setdefault(position, [])
        by_position[position].append(player)

    return by_position

# Function to group players by country, and per each country, by position
def group_by_country_and_position(squad_data):
    squad = squad_as_dict(squad_data)
    by_country = {}
    for player in squad:
        country = player['country']
        position = player['position']
        by_country.setdefault(country, {})
        by_country[country].setdefault(position, [])
        by_country[country][position].append(player)

    return by_country